### ISSUE TITLE
[FeatureRequest] Check before updating

### ISSUE THREAD

**Issue by ghost** [aimaat/RemoteUpdate#4]
It would be nice to have a "check" in the list with "Update", "Reboot","Script" where you can see the missing updates and decide if you want to install the updates.

I dont understand what the timer means when you click update?

Thank you!

**Comment by aimaat** [comment]
Just use the Update without the "AcceptAll" checkmark and use No on all updates. with this "workaround" you can see all available updates for that host.

The time information is just a little helper to know when you started the update procedure (and since 0.5.0.1 the time changes with a "Fin" prefix to show you the time when it finished). It is quite helpful if you update 20-30 servers simultaneously and have to do a second run or something else.

**Comment by aimaat** [comment]
The even better solution would be to use the "Script" option with "Get-WindowsUpdate | ft Title"
